 CLASS ztcl_categoria  DEFINITION
 PUBLIC
 FINAL
 CREATE PUBLIC
 FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS ztcl_categoria  IMPLEMENTATION.
 ENDCLASS.
